### ISSUE TITLE
Development stack deployment process

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/deploy-dev#5]
We need an easy way to deploy a full development stack for local testing. 

* [x] Docker-compose environment 
* [x] Documentation
* [ ] Train developers

**Comment by craig-willis** [comment]
@ThomasThelen We think this is ready to go.  Could you give it a try on your VM and let me know how it goes?

https://github.com/whole-tale/deploy-dev/blob/master/README.md

**Comment by ThomasThelen** [comment]
Sure thing. Thanks for putting this together!

**Comment by ThomasThelen** [comment]
I was able to go through the readme and deploy the stack with ease. The only note is that I manually ran `setup_girder` after seeing the error below.

```
docker stack deploy --compose-file=docker-stack.yml wt
Creating network wt_mongo
Creating network wt_celery
Creating network wt_traefik-net
Creating service wt_dashboard
Creating service wt_registry
Creating service wt_traefik
Creating service wt_mongo
Creating service wt_girder
Creating service wt_redis
./run_worker.sh
e352f86e892cbf716f4fb03d77726a91efc30ea15dcc2851515d5291da31a865
./setup_girder.py
Waiting for Girder to start
Traceback (most recent call last):
  File "./setup_girder.py", line 25, in <module>
    r = requests.get(api_url)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/requests/adapters.py", line 513, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='girder.vcap.me', port=80): Max retries exceeded with url: /api/v1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd32c559210>: Failed to establish a new connection: [Errno 111] Connection refused',))
Makefile:19: recipe for target 'dev' failed
make: *** [dev] Error 1
```

It would also be nice to throw a [dependencies install script](https://docs.docker.com/install/linux/docker-ce/ubuntu/#install-docker-ce-1) inside.

**Comment by ThomasThelen** [comment]
This issue can most likely be closed now that there are complete instructions and automated scripts to do the heavy lifting. I was able to re-deploy the development stack with ease on a new Ubuntu VM.
